### ISSUE TITLE
lack burn()

### ISSUE THREAD

**Issue by Lfh2msn** [aeternity/aex141-examples#1]
The example seems to be missing **burn()**

**Comment by arjanvaneersel** [comment]
It's not clear which example you're exactly referring to. Several examples have been provided, including an example of minting and burning.

`base_nft.aes` is an example of a uniqe NFT representing a single object.
`mintable_burnable.aes` is an example of an NFT with the mintable and burnable extension.
`swappable.aes` is and example of an NFT with the swappable extension.
`credential.aes` is an example of a mintable course graduation NFT smart contract.

**Comment by Lfh2msn** [comment]
> It's not clear which example you're exactly referring to. Several examples have been provided, including an example of minting and burning.
> 
> `base_nft.aes` is an example of a uniqe NFT representing a single object. `mintable_burnable.aes` is an example of an NFT with the mintable and burnable extension. `swappable.aes` is and example of an NFT with the swappable extension. `credential.aes` is an example of a mintable course graduation NFT smart contract.

 Well, it's just an example. I can't find burning in credential.aes

**Comment by arjanvaneersel** [comment]
Credential.aes is an example of an NFT used as a graduation credential. Such an NFT should be mintable, but not burnable in most cases. The reason for that is simple: Such a credential NFT is issued when someone passed -for example- a course's exam. Such a credential stays with the person. Even if it's a credential with limited validity (for example the exam has to be taken every X years to stay certified), then it's more common to implement an expiry date to the credential than to burn it. So the fact that this example doesn't have the burnable extension is not a mistake, but a choice based on common practice with credentials.

Of course there are exceptions possible. So if in your use case you'd need a burnable credential then you can do so. In `mintable_burnable.aes` you can see an example of implementing the burnable extension.

**Comment by Lfh2msn** [comment]
Thank you very much, I originally thought it was final NFT. Google translate brought me some troubles, now I am clear.
