### ISSUE TITLE
There is an error at line 77 of each examples contracts

### ISSUE THREAD

**Issue by Lfh2msn** [aeternity/aex141-examples#2]
Error line 77 in all sample files,

`require(String.length(name) >= 1, "STRING_TOO_SHORT_SYMBOL")`
Should be changed to
`require(String.length(symbol) >= 1, "STRING_TOO_SHORT_SYMBOL")`

**Comment by omar-saadoun** [comment]
Hi @Lfh2msn thanks for noticing , there is some updates to be made on both the standard and examples. In any case would you mind opening a pull request? @arjanvaneersel

**Comment by arjanvaneersel** [comment]
Great catch. I will open a PR.

**Comment by arjanvaneersel** [comment]
Solved with [commit 7e8c6fa823ec6a0a1059780db545530e11e7d3ec](https://github.com/aeternity/aex141-examples/commit/7e8c6fa823ec6a0a1059780db545530e11e7d3ec).
