### ISSUE TITLE
Invocation failed: “Reentrant call” - Intercontract call failure

### ISSUE THREAD

**Issue by Jkrish1011** [aeternity/aex141-examples#3]
I am trying to use the AEX-141 NFT standard for one of the projects that I am building.

My requirement is to interact with the deployed nft contract(whose address is passed in as a param) to my base contract and my base contract(a marketplace sortof) be controlling the nft’s ownership and other attributes.
But when I am making a intercontract contract call(my base contract to already deployed nft contract), I am getting an exception shown below.

Here is my base contract:

```
@compiler >= 6

include "String.aes"
include "Option.aes"
include "List.aes"
include "core/interfaces.aes"

payable contract SampleNFTInterContract =
    function tokensTransferable(_token : NFT, _tokenId : int) : bool =
        require(_token.is_approved_for_all(Call.caller, Contract.address) == true, "The HTLC contract must have been designated as an approved spender for the token")
        true
    
    public payable stateful entrypoint newContract(_tokenContract: NFT, _tokenId : int) : int = 
        tokensTransferable(_tokenContract, _tokenId)
```

But I am ending up with exception as shown below:

<img width="1037" alt="Screenshot 2022-06-23 at 6 27 05 AM" src="https://user-images.githubusercontent.com/21274245/175823352-ebba9c65-f513-4d03-89dc-8a3f0313a697.png">

What can be reason for this exception? How do I make the inter-contract call to NFT contract?

**Comment by omar-saadoun** [comment]
Hey @arjanvaneersel anyway you can support @Jkrish1011 ?

**Comment by arjanvaneersel** [comment]
Discussed here: https://forum.aeternity.com/t/invocation-failed-reentrant-call-intercontract-call-failure-in-sophia/10709/3
